<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Flit.Ict.Application</RootNamespace>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flit.Ict.Domain\Flit.Ict.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
