// <auto-generated />
using System;
using Flit.Consultas.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Consultas.Api.Persistence.Migrations
{
    [DbContext(typeof(ConsultasDb))]
    [Migration("20261007131802_HU13348_ValoresMockAvaluo")]
    partial class HU13348_ValoresMockAvaluo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("consultas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.AvisoProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("proveedor");

                    b.Property<DateTimeOffset>("RecibidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibido_en");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_avisos");

                    b.HasIndex("ReferenciaId", "RecibidoEn")
                        .HasDatabaseName("ix_avisos_referencia");

                    b.ToTable("avisos", "consultas");
                });

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.ConfiguracionEmpresa", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("AvaluosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("avaluos");

                    b.Property<string>("CadenasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("cadenas");

                    b.Property<int?>("FailoverTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("failover_timeout_ms");

                    b.Property<string>("FuenteMultas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuente_multas");

                    b.HasKey("TenantId")
                        .HasName("pk_configuracion_empresa");

                    b.ToTable("configuracion_empresa", "consultas");
                });

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.ConsumoConsulta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DesdeCache")
                        .HasColumnType("boolean")
                        .HasColumnName("desde_cache");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuente");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("integer")
                        .HasColumnName("latencia_ms");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("producto");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("proveedor");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resultado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_consumo");

                    b.HasIndex("TenantId", "OcurridoEn")
                        .HasDatabaseName("ix_consumo_empresa_fecha");

                    b.ToTable("consumo", "consultas");
                });

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.ValidacionKyverum", b =>
                {
                    b.Property<Guid>("ValidacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("validacion_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("producto");

                    b.Property<string>("SecretoCifrado")
                        .HasColumnType("text")
                        .HasColumnName("secreto_cifrado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verification_id");

                    b.HasKey("ValidacionId")
                        .HasName("pk_validaciones_kyverum");

                    b.ToTable("validaciones_kyverum", "consultas");
                });

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.ValorMockAvaluo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("clave");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuente");

                    b.Property<decimal>("ValorCop")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_cop");

                    b.HasKey("Id")
                        .HasName("pk_valores_mock_avaluo");

                    b.HasIndex("Clave", "Fuente")
                        .IsUnique()
                        .HasDatabaseName("uq_valores_mock_avaluo");

                    b.ToTable("valores_mock_avaluo", "consultas");
                });

            modelBuilder.Entity("Flit.Platform.Sdk.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "consultas");
                });

            modelBuilder.Entity("Flit.Platform.Sdk.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("routing_key");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pendientes")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox", "consultas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
