// <auto-generated />
using System;
using Flit.Consultas.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Consultas.Api.Persistence.Migrations
{
    [DbContext(typeof(ConsultasDb))]
    [Migration("20261007000456_ConfiguracionPorEmpresa")]
    partial class ConfiguracionPorEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("consultas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Consultas.Api.Persistence.ConfiguracionEmpresa", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("AvaluosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("avaluos");

                    b.Property<string>("CadenasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("cadenas");

                    b.Property<int?>("FailoverTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("failover_timeout_ms");

                    b.Property<string>("FuenteMultas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuente_multas");

                    b.HasKey("TenantId")
                        .HasName("pk_configuracion_empresa");

                    b.ToTable("configuracion_empresa", "consultas");
                });

            modelBuilder.Entity("Flit.Platform.Sdk.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "consultas");
                });

            modelBuilder.Entity("Flit.Platform.Sdk.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("routing_key");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pendientes")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox", "consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
