// <auto-generated />
using System;
using Flit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Infrastructure.Migrations
{
    [DbContext(typeof(FlitDbContext))]
    [Migration("20260619051114_TramitesTraspasoDevSeed")]
    partial class TramitesTraspasoDevSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legal_name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("TenantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tenant_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_tenants_code");

                    b.ToTable("tenants", "identity");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "security");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_credentials");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_credentials_user_id");

                    b.ToTable("user_credentials", "security");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.UserTempSuspension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_temp_suspensions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_temp_suspensions_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_user_temp_suspensions_tenant_id_user_id");

                    b.ToTable("user_temp_suspensions", "security");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ConformationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProcedureEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_entity_id");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_type_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValidationProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_profile")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_conformation_rules");

                    b.HasIndex("ProcedureEntityId")
                        .HasDatabaseName("ix_conformation_rules_procedure_entity_id");

                    b.HasIndex("ProcedureTypeId", "ProcedureEntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_conformation_rules_type_entity");

                    b.ToTable("conformation_rules", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ConsultationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EntityScope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_scope");

                    b.Property<Guid>("ExternalDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_data_source_id");

                    b.Property<string>("ExternalRefs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_refs")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PersonType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("person_type");

                    b.Property<string>("RequestSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_schema")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("RequiredFieldKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_field_keys")
                        .HasDefaultValueSql("'[]'");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_consultation_templates");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_consultation_templates_code");

                    b.HasIndex("ExternalDataSourceId")
                        .HasDatabaseName("ix_consultation_templates_external_data_source_id");

                    b.ToTable("consultation_templates", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ExternalDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("none")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalRefs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_refs")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_ms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_external_data_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_external_data_sources_code");

                    b.ToTable("external_data_sources", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.FieldApiBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ExternalDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_data_source_id");

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_field_id");

                    b.Property<string>("RequestMapping")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_mapping")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ResponseMapping")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_mapping")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_event");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_field_api_bindings");

                    b.HasIndex("ExternalDataSourceId")
                        .HasDatabaseName("ix_field_api_bindings_external_data_source_id");

                    b.HasIndex("FormFieldId")
                        .HasDatabaseName("ix_field_api_bindings_form_field_id");

                    b.ToTable("field_api_bindings", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("ConsultationTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_template_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<string>("LockReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lock_reason");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<Guid>("ProcedureSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_section_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValidationSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_schema")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_form_fields");

                    b.HasIndex("ConsultationTemplateId")
                        .HasDatabaseName("ix_form_fields_consultation_template_id");

                    b.HasIndex("ProcedureSectionId", "FieldKey")
                        .IsUnique()
                        .HasDatabaseName("uq_form_fields_section_key");

                    b.ToTable("form_fields", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalRefs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_refs")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_entities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_entities_code");

                    b.ToTable("procedure_entities", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("ChecklistEstado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("checklist_estado")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ModalidadEntrada")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("matricula_inicial")
                        .HasColumnName("modalidad_entrada");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_type_id");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reference_number");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("RulesSnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rules_snapshot_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipologiaCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipologia_codigo");

                    b.Property<Guid?>("TransitOfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("transit_office_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instances");

                    b.HasIndex("ProcedureTypeId")
                        .HasDatabaseName("ix_procedure_instances_procedure_type_id");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_instances_tenant_reference");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_procedure_instances_tenant_id_status_created_at");

                    b.ToTable("procedure_instances", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ProcedureEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_entity_id");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_actors");

                    b.HasIndex("ProcedureEntityId")
                        .HasDatabaseName("ix_procedure_instance_actors_procedure_entity_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_procedure_instance_actors_tenant_id");

                    b.HasIndex("ProcedureInstanceId", "ProcedureEntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_instance_actors_instance_entity");

                    b.ToTable("procedure_instance_actors", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename");

                    b.Property<string>("Mimetype")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mimetype");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("source");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_attachments");

                    b.HasIndex("ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_attachments_procedure_instance_id");

                    b.HasIndex("TenantId", "ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_attachments_tenant_id_instance");

                    b.ToTable("procedure_instance_attachments", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceCommercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Causal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("causal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Derechos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("derechos");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metodo_pago");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<decimal?>("TasaImpuesto")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tasa_impuesto");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorVenta")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_venta");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_commercial");

                    b.HasIndex("ProcedureInstanceId")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_instance_commercial_instance");

                    b.ToTable("procedure_instance_commercial", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_events");

                    b.HasIndex("ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_events_procedure_instance_id");

                    b.HasIndex("TenantId", "ProcedureInstanceId", "CreatedAt")
                        .HasDatabaseName("ix_procedure_instance_events_tenant_id_instance_created");

                    b.ToTable("procedure_instance_events", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("field_key");

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_field_id");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_field_values");

                    b.HasIndex("FormFieldId")
                        .HasDatabaseName("ix_procedure_instance_field_values_form_field_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_procedure_instance_field_values_tenant_id");

                    b.HasIndex("ProcedureInstanceId", "FieldKey")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_instance_field_values_instance_key");

                    b.ToTable("procedure_instance_field_values", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstancePreflightSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Checks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("checks")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Overall")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("overall");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_preflight_snapshots");

                    b.HasIndex("ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_preflight_snapshots_procedure_instance_id");

                    b.HasIndex("TenantId", "ProcedureInstanceId", "CreatedAt")
                        .HasDatabaseName("ix_procedure_instance_preflight_snapshots_tenant_id_instance_created");

                    b.ToTable("procedure_instance_preflight_snapshots", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_instance_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_procedure_instance_status_history");

                    b.HasIndex("ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_status_history_procedure_instance_id");

                    b.HasIndex("TenantId", "ProcedureInstanceId")
                        .HasDatabaseName("ix_procedure_instance_status_history_tenant_id_instance");

                    b.ToTable("procedure_instance_status_history", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("single")
                        .HasColumnName("layout");

                    b.Property<Guid>("ProcedureStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_step_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_sections");

                    b.HasIndex("ProcedureStepId")
                        .HasDatabaseName("ix_procedure_sections_procedure_step_id");

                    b.ToTable("procedure_sections", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_type_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_steps");

                    b.HasIndex("ProcedureTypeId")
                        .HasDatabaseName("ix_procedure_steps_procedure_type_id");

                    b.ToTable("procedure_steps", "tramites");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalRefs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_refs")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("family");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("publication_status");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_procedure_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_types_code");

                    b.ToTable("procedure_types", "tramites");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.PasswordResetToken", b =>
                {
                    b.HasOne("Flit.Infrastructure.Persistence.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.UserCredential", b =>
                {
                    b.HasOne("Flit.Infrastructure.Persistence.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Entities.Security.UserTempSuspension", b =>
                {
                    b.HasOne("Flit.Infrastructure.Persistence.Entities.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_temp_suspensions_tenants");

                    b.HasOne("Flit.Infrastructure.Persistence.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_temp_suspensions_users");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ConformationRule", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureEntity", "ProcedureEntity")
                        .WithMany()
                        .HasForeignKey("ProcedureEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conformation_rules_procedure_entities_procedure_entity_id");

                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureType", "ProcedureType")
                        .WithMany("ConformationRules")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conformation_rules_procedure_types_procedure_type_id");

                    b.Navigation("ProcedureEntity");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ConsultationTemplate", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ExternalDataSource", "ExternalDataSource")
                        .WithMany()
                        .HasForeignKey("ExternalDataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consultation_templates_external_data_sources_external_data_");

                    b.Navigation("ExternalDataSource");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.FieldApiBinding", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ExternalDataSource", "ExternalDataSource")
                        .WithMany()
                        .HasForeignKey("ExternalDataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_api_bindings_external_data_sources_external_data_sour");

                    b.HasOne("Flit.Tramites.Domain.Entities.FormField", "FormField")
                        .WithMany()
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_api_bindings_form_fields_form_field_id");

                    b.Navigation("ExternalDataSource");

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.FormField", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ConsultationTemplate", "ConsultationTemplate")
                        .WithMany()
                        .HasForeignKey("ConsultationTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_fields_consultation_templates");

                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureSection", "ProcedureSection")
                        .WithMany("FormFields")
                        .HasForeignKey("ProcedureSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_fields_procedure_sections_procedure_section_id");

                    b.Navigation("ConsultationTemplate");

                    b.Navigation("ProcedureSection");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstance", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureType", "ProcedureType")
                        .WithMany()
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instances_procedure_types");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceActor", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureEntity", "ProcedureEntity")
                        .WithMany()
                        .HasForeignKey("ProcedureEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_actors_procedure_entities");

                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("Actors")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_actors_procedure_instances");

                    b.Navigation("ProcedureEntity");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceAttachment", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("Attachments")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_attachments_procedure_instances");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceCommercial", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithOne("Commercial")
                        .HasForeignKey("Flit.Tramites.Domain.Entities.ProcedureInstanceCommercial", "ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_commercial_procedure_instances");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceEvent", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("Events")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_events_procedure_instances");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceFieldValue", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.FormField", "FormField")
                        .WithMany()
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_field_values_form_fields");

                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_field_values_procedure_instances");

                    b.Navigation("FormField");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstancePreflightSnapshot", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("PreflightSnapshots")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_preflight_snapshots_procedure_instances");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstanceStatusHistory", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_instance_status_history_procedure_instances");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureSection", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureStep", "ProcedureStep")
                        .WithMany("Sections")
                        .HasForeignKey("ProcedureStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_sections_procedure_steps_procedure_step_id");

                    b.Navigation("ProcedureStep");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureStep", b =>
                {
                    b.HasOne("Flit.Tramites.Domain.Entities.ProcedureType", "ProcedureType")
                        .WithMany("Steps")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_steps_procedure_types_procedure_type_id");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureInstance", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Attachments");

                    b.Navigation("Commercial");

                    b.Navigation("Events");

                    b.Navigation("FieldValues");

                    b.Navigation("PreflightSnapshots");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureSection", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureStep", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Flit.Tramites.Domain.Entities.ProcedureType", b =>
                {
                    b.Navigation("ConformationRules");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
