<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Flit.Analytics.Application</RootNamespace>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flit.Queries.Domain\Flit.Queries.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
