<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Flit.Tramites.Domain</RootNamespace>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

</Project>
