<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Flit.Analytics.Application.Tests</RootNamespace>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Flit.Analytics.Application\Flit.Analytics.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

</Project>
