-- ─────────────────────────────────────────────────────────────────────────────
-- HU #10919 (Feature #10918) — Catálogo de equivalencia clasificación → plantilla FUR.
--
-- Tabla de decisión que determina qué plantilla de FUR (AUTOMOTOR / MAQUINARIA /
-- REMOLQUES) aplica según la clasificación del vehículo (vehicle_class del proveedor).
-- Catálogo GLOBAL (sin tenant). Idempotente: ON CONFLICT (classification) DO UPDATE.
-- El resolver (FurTemplateResolver) normaliza (mayúsculas/sin tildes/trim) al buscar;
-- aquí la clasificación se guarda literal como en la fuente (vehicle_classification_fur.csv).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tramites.vehicle_classification_fur (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    classification  text NOT NULL,
    template_format text NOT NULL,
    field_to_fill   text NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz NULL,
    CONSTRAINT uq_vehicle_classification_fur_classification UNIQUE (classification),
    CONSTRAINT ck_vehicle_classification_fur_format
        CHECK (template_format IN ('AUTOMOTOR', 'MAQUINARIA', 'REMOLQUES'))
);

COMMENT ON TABLE tramites.vehicle_classification_fur IS
    'HU #10919 — Equivalencia clasificación de vehículo → plantilla de FUR (AUTOMOTOR/MAQUINARIA/REMOLQUES). Catálogo global.';

COMMENT ON COLUMN tramites.vehicle_classification_fur.field_to_fill IS
    'Identificador del campo del overlay FUR a diligenciar o marcar para esta clasificación (casilla numeral 4 u homóloga).';

INSERT INTO tramites.vehicle_classification_fur (classification, template_format, field_to_fill)
VALUES
    ('AUTOMOVIL', 'AUTOMOTOR', 'AUTOMOVIL'),
    ('BUS', 'AUTOMOTOR', 'BUS'),
    ('BUSETA', 'AUTOMOTOR', 'BUSETA'),
    ('CAMION', 'AUTOMOTOR', 'CAMION'),
    ('CAMIONETA', 'AUTOMOTOR', 'CAMIONETA'),
    ('CAMPERO', 'AUTOMOTOR', 'CAMPERO'),
    ('CICLOMOTOR', 'AUTOMOTOR', 'MOTOTRICICLO'),
    ('CUADRICICLO', 'AUTOMOTOR', 'CUATRIMOTO'),
    ('CUATRIMOTO', 'AUTOMOTOR', 'CUATRIMOTO'),
    ('MICROBUS', 'AUTOMOTOR', 'MICROBUS'),
    ('MOTOCARRO', 'AUTOMOTOR', 'MOTOCARRO'),
    ('MOTOCICLETA', 'AUTOMOTOR', 'MOTOCICLETA'),
    ('MOTOTRICICLO', 'AUTOMOTOR', 'MOTOTRICICLO'),
    ('SIN CLASE', 'AUTOMOTOR', 'OTRO'),
    ('TRACTOCAMION', 'AUTOMOTOR', 'TRACTOCAMION'),
    ('TRICIMOTO', 'AUTOMOTOR', 'MOTOTRICICLO'),
    ('VOLQUETA', 'AUTOMOTOR', 'VOLQUETA'),
    ('ABONADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('ALZADORA DE CAÑA', 'MAQUINARIA', 'AGRICOLA'),
    ('APILADOR', 'MAQUINARIA', 'INDUSTRIAL'),
    ('APLANADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('AUTOHORMIGONERA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('BARREDORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('BULDOZER', 'MAQUINARIA', 'CONSTRUCCION'),
    ('CAMBIADORA DE RIEL', 'MAQUINARIA', 'INDUSTRIAL'),
    ('CAMION CARGA EXTENSA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('CAMION CISTERNA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('CAMIÓN DE RESCATE', 'MAQUINARIA', 'INDUSTRIAL'),
    ('CAMIÓN ESCALERA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('CAMIÓN ESTÉRIL', 'MAQUINARIA', 'CONSTRUCCION'),
    ('CAMIÓN GRÚA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('CAMIÓN TIJERA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('CARGADOR', 'MAQUINARIA', 'AGRICOLA'),
    ('CARRETILLA APILADORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('CARRETILLA ELEVADORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('COMPACTADOR', 'MAQUINARIA', 'CONSTRUCCION'),
    ('COMPOSTADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('CORTADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('COSECHADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('CRIBAS', 'MAQUINARIA', 'AGRICOLA'),
    ('DISTRIBUIDOR AUTOPROPELIDO DE FERTILIZANTES', 'MAQUINARIA', 'AGRICOLA'),
    ('DRAGA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('DUMPER (VOLQUETA ARTICULADA)', 'MAQUINARIA', 'CONSTRUCCION'),
    ('EQUIPO DE DEMOLICION', 'MAQUINARIA', 'CONSTRUCCION'),
    ('EXCAVADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('FERTILIZADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('FINICHER', 'MAQUINARIA', 'CONSTRUCCION'),
    ('FRESADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('FUMIGADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('GATOR', 'MAQUINARIA', 'AGRICOLA'),
    ('GRUA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('HORMIGONERA PARA TÚNELES', 'MAQUINARIA', 'CONSTRUCCION'),
    ('IRRIGADOR', 'MAQUINARIA', 'CONSTRUCCION'),
    ('JUMBO DE PERFORACION', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MANIPULADOR CARGADOR TELESCOPICO', 'MAQUINARIA', 'CONSTRUCCION'),
    ('MANIPULADOR TELESCOPICO', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MAQUINA BARREDORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MAQUINARIA AGRICOLA', 'MAQUINARIA', 'AGRICOLA'),
    ('MAQUINARIA CONSTRUCCION', 'MAQUINARIA', 'CONSTRUCCION'),
    ('MAQUINARIA INDUSTRIAL', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MAQUINA TRAZADORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MINICARGADOR', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MINI EXCAVADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('MINI RETROEXCAVADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('MONTACARGAS', 'MAQUINARIA', 'INDUSTRIAL'),
    ('MOTONIVELADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('MOTOTRAÍLLA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('PALA DRAGA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('PALA FRONTAL', 'MAQUINARIA', 'CONSTRUCCION'),
    ('PAVIMENTADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('PENETROMETRO AUTOPROPULSADO', 'MAQUINARIA', 'INDUSTRIAL'),
    ('PERFILADORA DE PAVIMENTO EN FRIO', 'MAQUINARIA', 'CONSTRUCCION'),
    ('PERFORADORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('PILOTEADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('PLATAFORMA DE ELEVACION', 'MAQUINARIA', 'INDUSTRIAL'),
    ('PRENSA HIDRAULICA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('PULVERIZADOR AGRICOLA', 'MAQUINARIA', 'AGRICOLA'),
    ('RECICLADORA', 'MAQUINARIA', 'INDUSTRIAL'),
    ('RECICLADORA DE PAVIMENTOS', 'MAQUINARIA', 'CONSTRUCCION'),
    ('RETROCARGADOR', 'MAQUINARIA', 'CONSTRUCCION'),
    ('RETROEXCAVADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('TALADRO', 'MAQUINARIA', 'INDUSTRIAL'),
    ('TALADRO PERFORACION POZO PETROLERO', 'MAQUINARIA', 'INDUSTRIAL'),
    ('TRACTOR', 'MAQUINARIA', 'AGRICOLA'),
    ('TRACTOR SOBRE ORUGA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('TRANSPLANTADORA', 'MAQUINARIA', 'AGRICOLA'),
    ('TRITURADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('UTILERO', 'MAQUINARIA', 'AGRICOLA'),
    ('VIBROCOMPACTADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('VOLCO', 'MAQUINARIA', 'INDUSTRIAL'),
    ('VOLQUETA SOBRE ORUGA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('ZANJADORA', 'MAQUINARIA', 'CONSTRUCCION'),
    ('MAQ. CONSTRUCCION O MINERA', 'REMOLQUES', 'SIMILAR'),
    ('REMOLQUE', 'REMOLQUES', 'REMOLQUE'),
    ('REMOLQUE Y SEMIRREMOLQUE', 'REMOLQUES', 'MULTIMODULAR'),
    ('SEMIREMOLQUE', 'REMOLQUES', 'SEMIREMOLQUE')
ON CONFLICT (classification) DO UPDATE SET
    template_format = EXCLUDED.template_format,
    field_to_fill = EXCLUDED.field_to_fill,
    updated_at = now();
