-- ─────────────────────────────────────────────────────────────────────────────
-- HU #10919 (Feature #10918) — Catálogo de equivalencia clasificación → plantilla FUR.
--
-- Tabla de decisión que determina qué plantilla de FUR (AUTOMOTOR / MAQUINARIA /
-- REMOLQUES) aplica según la clasificación del vehículo (vehicle_class del proveedor).
-- Catálogo GLOBAL (sin tenant). Idempotente: ON CONFLICT (classification) DO NOTHING.
-- El resolver (FurTemplateResolver) normaliza (mayúsculas/sin tildes/trim) al buscar;
-- aquí la clasificación se guarda literal como en la fuente (vehicle_classification_fur.csv).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tramites.vehicle_classification_fur (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    classification  text NOT NULL,
    template_format text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz NULL,
    CONSTRAINT uq_vehicle_classification_fur_classification UNIQUE (classification),
    CONSTRAINT ck_vehicle_classification_fur_format
        CHECK (template_format IN ('AUTOMOTOR', 'MAQUINARIA', 'REMOLQUES'))
);

COMMENT ON TABLE tramites.vehicle_classification_fur IS
    'HU #10919 — Equivalencia clasificación de vehículo → plantilla de FUR (AUTOMOTOR/MAQUINARIA/REMOLQUES). Catálogo global.';

INSERT INTO tramites.vehicle_classification_fur (classification, template_format)
VALUES
    ('ABONADORA', 'MAQUINARIA'),
    ('ALZADORA DE CAÑA', 'MAQUINARIA'),
    ('APILADOR', 'MAQUINARIA'),
    ('APLANADORA', 'MAQUINARIA'),
    ('AUTOHORMIGONERA', 'MAQUINARIA'),
    ('AUTOMOVIL', 'AUTOMOTOR'),
    ('BARREDORA', 'MAQUINARIA'),
    ('BULDOZER', 'MAQUINARIA'),
    ('BUS', 'AUTOMOTOR'),
    ('BUSETA', 'AUTOMOTOR'),
    ('CAMBIADORA DE RIEL', 'MAQUINARIA'),
    ('CAMION CARGA EXTENSA', 'MAQUINARIA'),
    ('CAMION CISTERNA', 'MAQUINARIA'),
    ('CAMIÓN DE RESCATE', 'MAQUINARIA'),
    ('CAMIÓN ESCALERA', 'MAQUINARIA'),
    ('CAMIÓN ESTÉRIL', 'MAQUINARIA'),
    ('CAMIÓN GRÚA', 'MAQUINARIA'),
    ('CAMIÓN TIJERA', 'MAQUINARIA'),
    ('CAMIONETA', 'AUTOMOTOR'),
    ('CAMPERO', 'AUTOMOTOR'),
    ('CARGADOR', 'MAQUINARIA'),
    ('CARRETILLA APILADORA', 'MAQUINARIA'),
    ('CARRETILLA ELEVADORA', 'MAQUINARIA'),
    ('CICLOMOTOR', 'AUTOMOTOR'),
    ('COMPACTADOR', 'MAQUINARIA'),
    ('COMPOSTADORA', 'MAQUINARIA'),
    ('CORTADORA', 'MAQUINARIA'),
    ('COSECHADORA', 'MAQUINARIA'),
    ('CRIBAS', 'MAQUINARIA'),
    ('CUADRICICLO', 'AUTOMOTOR'),
    ('CUATRIMOTO', 'AUTOMOTOR'),
    ('DISTRIBUIDOR AUTOPROPELIDO DE FERTILIZANTES', 'MAQUINARIA'),
    ('DRAGA', 'MAQUINARIA'),
    ('DUMPER (VOLQUETA ARTICULADA)', 'MAQUINARIA'),
    ('EQUIPO DE DEMOLICION', 'MAQUINARIA'),
    ('EXCAVADORA', 'MAQUINARIA'),
    ('FERTILIZADORA', 'MAQUINARIA'),
    ('FINICHER', 'MAQUINARIA'),
    ('FRESADORA', 'MAQUINARIA'),
    ('FUMIGADORA', 'MAQUINARIA'),
    ('GATOR', 'MAQUINARIA'),
    ('GRUA', 'MAQUINARIA'),
    ('HORMIGONERA PARA TÚNELES', 'MAQUINARIA'),
    ('IRRIGADOR', 'MAQUINARIA'),
    ('JUMBO DE PERFORACION', 'MAQUINARIA'),
    ('MANIPULADOR CARGADOR TELESCOPICO', 'MAQUINARIA'),
    ('MANIPULADOR TELESCOPICO', 'MAQUINARIA'),
    ('MAQ. CONSTRUCCION O MINERA', 'REMOLQUES'),
    ('MAQUINA BARREDORA', 'MAQUINARIA'),
    ('MAQUINA TRAZADORA', 'MAQUINARIA'),
    ('MICROBUS', 'AUTOMOTOR'),
    ('MINI EXCAVADORA', 'MAQUINARIA'),
    ('MINI RETROEXCAVADORA', 'MAQUINARIA'),
    ('MINICARGADOR', 'MAQUINARIA'),
    ('MONTACARGAS', 'MAQUINARIA'),
    ('MOTOCARRO', 'AUTOMOTOR'),
    ('MOTOCICLETA', 'AUTOMOTOR'),
    ('MOTONIVELADORA', 'MAQUINARIA'),
    ('MOTOTRAÍLLA', 'MAQUINARIA'),
    ('MOTOTRICICLO', 'AUTOMOTOR'),
    ('PALA DRAGA', 'MAQUINARIA'),
    ('PALA FRONTAL', 'MAQUINARIA'),
    ('PAVIMENTADORA', 'MAQUINARIA'),
    ('PENETROMETRO AUTOPROPULSADO', 'MAQUINARIA'),
    ('PERFILADORA DE PAVIMENTO EN FRIO', 'MAQUINARIA'),
    ('PERFORADORA', 'MAQUINARIA'),
    ('PILOTEADORA', 'MAQUINARIA'),
    ('PLATAFORMA DE ELEVACION', 'MAQUINARIA'),
    ('PRENSA HIDRAULICA', 'MAQUINARIA'),
    ('PULVERIZADOR AGRICOLA', 'MAQUINARIA'),
    ('RECICLADORA', 'MAQUINARIA'),
    ('RECICLADORA DE PAVIMENTOS', 'MAQUINARIA'),
    ('REMOLQUE', 'REMOLQUES'),
    ('REMOLQUE Y SEMIRREMOLQUE', 'REMOLQUES'),
    ('RETROCARGADOR', 'MAQUINARIA'),
    ('RETROEXCAVADORA', 'MAQUINARIA'),
    ('SEMIREMOLQUE', 'REMOLQUES'),
    ('SIN CLASE', 'AUTOMOTOR'),
    ('TALADRO', 'MAQUINARIA'),
    ('TALADRO PERFORACION POZO PETROLERO', 'MAQUINARIA'),
    ('TRACTOCAMION', 'AUTOMOTOR'),
    ('TRACTOR', 'MAQUINARIA'),
    ('TRACTOR SOBRE ORUGA', 'MAQUINARIA'),
    ('TRANSPLANTADORA', 'MAQUINARIA'),
    ('TRICIMOTO', 'AUTOMOTOR'),
    ('TRITURADORA', 'MAQUINARIA'),
    ('UTILERO', 'MAQUINARIA'),
    ('VIBROCOMPACTADORA', 'MAQUINARIA'),
    ('VOLCO', 'MAQUINARIA'),
    ('VOLQUETA', 'AUTOMOTOR'),
    ('VOLQUETA SOBRE ORUGA', 'MAQUINARIA'),
    ('ZANJADORA', 'MAQUINARIA'),
    ('MAQUINARIA AGRICOLA', 'MAQUINARIA'),
    ('MAQUINARIA INDUSTRIAL', 'MAQUINARIA'),
    ('MAQUINARIA CONSTRUCCION', 'MAQUINARIA'),
    ('CAMION', 'AUTOMOTOR')
ON CONFLICT (classification) DO NOTHING;
