<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Flit.Modules.Security.Application.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Flit.Modules.Security.Application\Flit.Modules.Security.Application.csproj" />
    <ProjectReference Include="..\..\src\Flit.Modules.Security.Domain\Flit.Modules.Security.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
